### ISSUE TITLE
solve_l1r_l2_svc() uninitialized variable

### ISSUE THREAD

**Issue by myeung2** [cjlin1/liblinear#31]
Hi, thanks for a great tool. With regard to this compilation warning:

linear.cpp: In function `void train_one(const problem*, const parameter*, double*, double, double)':
linear.cpp:1365: warning: 'loss_old' might be used uninitialized in this function

Can I just initialize "loss_old" to 0? Thanks.

**Comment by simsong** [comment]
This issue was moved to angleto/liblinear#9

**Comment by cjlin1** [comment]
Thanks. THis will be updated in the next release. BTW, under which compiler this message occurs? I don't see that on linux
