### ISSUE TITLE
Having difficulty installing and using Python version of liblinear

### ISSUE THREAD

**Issue by drussellmrichie** [cjlin1/liblinear#34]
Here's what I've done:

1. Downloaded the entire liblinear library.
2. In a terminal (on my mac), I `cd` to the downloaded folder.
3. Type `make` in the main folder, and then also in the `/python` folder. This generates a `liblinear.so.3` file in the `/python` folder.
4. I then start an ipython session (2.7 running in a conda virtual env) in the `/python` folder.
5. Whether I type `import liblinear` or `import liblinearutil`, I get the following error: `Exception: LIBLINEAR library not found.`

If it helps: I need liblinear because I'm trying to use [a different library that requires it](https://github.com/jjessyli/speciteller).

**Comment by poornagurram** [comment]
What was the solution for this problem

**Comment by drussellmrichie** [comment]
Unfortunately a colleague walked me through the process verbally, so I don't have a record anymore of what I did (and I haven't used the library requiring liblinear since the summer). Sorry! :-(

**Comment by poornagurram** [comment]
It's ok. I figured it out. Thank you for the reply 👍
