### ISSUE TITLE
`train` fails to read input file

### ISSUE THREAD

**Issue by cconrads-scicomp** [cjlin1/liblinear#36]
According to the [LIBLINEAR website](https://www.csie.ntu.edu.tw/~cjlin/liblinear/), liblinear and libsvm use the same input format. On my computer, `train` signals an error when it reads an input file that is successfully parsed by libsvm. I traced the different behavior to line 395 in `train.c`:
```c++
		inst_max_index = 0; // strtol gives 0 if wrong format
```
In libsvm, the same variable is initialized to `-1` and changing `inst_max_index` allows `train` to read the file successfully, too.

**Comment by leepei** [comment]
It looks very likely from both issues you posted that your data set feature enumeration starts with 0, while libsvm and liblinear both require it starts from 1. The counter 0 in libsvm is allowed for precomputed kernel only.

**Comment by cconrads-scicomp** [comment]
You are right leepei and here is the [relevant line in the libsvm README](https://github.com/cjlin1/libsvm/blob/88a1881f03ca139beff93170d7e6f36477fabe54/README#L64):

```
The pair <index>:<value> gives a feature
(attribute) value: <index> is an integer starting from 1 and <value>
is a real number.
```

**Comment by cconrads-scicomp** [comment]
@leepei Thank you for the quick response.
