### ISSUE TITLE
Version numbers not monotonically increasing

### ISSUE THREAD

**Issue by ilovezfs** [cjlin1/liblinear#40]
```
Josephs-MacBook-Pro:~ joe$ brew irb 
==> Interactive Homebrew Shell
Example commands available with: brew irb --examples
irb(main):001:0> Version.new("2.2") > Version.new("2.11")
=> false
irb(main):002:0> 
```
This will cause a problem upgrading the Homebrew formula. Would it be possible to rename the release and tarball `2.20` instead of `2.2` or something along those lines?

**Comment by infwinston** [comment]
Hi @ilovezfs,
Just to clarify, the version number `2.2` you are referring to is indeed from LIBLINEAR's website, right?
From github we don't see there is something like version number.

**Comment by ilovezfs** [comment]
@infwinston right:

```
irb(main):003:0> Version.detect("https://www.csie.ntu.edu.tw/~cjlin/liblinear/oldfiles/liblinear-2.11.tar.gz", {})
=> #<Version::FromURL:0x00007fbe11980b30 @version="2.11">
irb(main):004:0> Version.detect("https://www.csie.ntu.edu.tw/~cjlin/liblinear/oldfiles/liblinear-2.2.tar.gz", {})
=> #<Version::FromURL:0x00007fbe118e9a00 @version="2.2">
```

**Comment by infwinston** [comment]
@ilovezfs Thanks!
We've renamed it to `2.20` and released, please check it.

**Comment by ilovezfs** [comment]
Perfect. Thank you! I have :ship:'d 2.20 in Homebrew now :) See https://github.com/Homebrew/homebrew-core/pull/21469.
