### ISSUE TITLE
OnevsOne updated library?

### ISSUE THREAD

**Issue by stpr-unb** [cjlin1/liblinear#54]
Hello,

I am trying to implement OvO multiclass logistic regression classifier in MATLAB, but the version on the [webpage](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/#liblinear_for_one_versus_one_multi_class_classification) for the OvO code is older than the current version of LIBLINEAR (2.20 vs 2.30). Would it be possible to obtain an updated version for this code? Thanks in advance.

**Comment by cjlin1** [comment]
The latest version will be uploaded in one month. Thanks

**Comment by stpr-unb** [comment]
Thank you. A follow up question - I should be able to drop it into the LIBLINEAR directory and compile the mex file as I would for the standard LIBLINEAR correct?

**Comment by cjlin1** [comment]
In the released ovo extension the matlab directory was removed because 
we didn't intend to maintain it.. But I think we have the code (note 
that things in the master cannot be used due to the change on the number 
of w vectors)
We can check this as well while doing the update

**Comment by stpr-unb** [comment]
Thanks a lot, I would appreciate it if you can look into the MATLAB generating code as well.

**Comment by ZYQue** [comment]
The updated ovo is available now, and it supports MATLAB. Please see the new release.
