### ISSUE TITLE
Use liblinear on windows

### ISSUE THREAD

**Issue by PingHGao** [cjlin1/liblinear#63]
I installed `liblinear` through `pip install liblinear` successfully. But got error `ModuleNotFoundError: No module named 'liblinear'`.

I download the zip file from github and included the `../python` dir into `sys.path`, the import error still remains. 

How should I install it on windows for python. Thanks!

**Comment by cjlin1** [comment]
Please check python/README of liblinear
(don't download from github. Check file at liblinear homepage. A dll 
file is provided there)
