### ISSUE TITLE
How to improve accuracy?

### ISSUE THREAD

**Issue by cheeyeo** [cjlin1/liblinear#7]
I'm running liblinear on text classification using -s 0 and -s 6 in order to get probability estimates of a multiclass classification task.

I read through the guides, sites, documents, feature scaling etc but the accuracy of each classifier is always low ? e.g. 14% 

How do I further improve the accuracy of the classifier?

Any help most useful

**Comment by simsong** [comment]
This issue was moved to angleto/liblinear#22
