### ISSUE TITLE
Compilation error for multi-threaded version

### ISSUE THREAD

**Issue by FrontierSetter** [cjlin1/liblinear#75]
I directly execute the "make" command in the unzipped directory, and got the following error:

> g++ -Wall -Wconversion -O3 -fPIC -fopenmp -c -o newton.o newton.cpp
g++ -Wall -Wconversion -O3 -fPIC -fopenmp -c -o linear.o linear.cpp
linear.cpp: In member function 'virtual double l2r_erm_fun::fun(double*)':
linear.cpp:244:70: error: 'l2r_erm_fun::wTw' is not a variable in clause 'reduction'
 #pragma omp parallel for private(i) reduction(+:wTw) schedule(static)
                                                                      ^
make: *** [linear.o] Error 1

The version I use is liblinear-multicore-2.43-2 from the official website.
How can I solve it, thank you.

**Comment by cjlin1** [comment]
which version of g++ are you using?
I can run make without problem

**Comment by FrontierSetter** [comment]
@cjlin1 Thanks for your reply. the error still persists after I updated with "yum install gcc". The g++ version I am using now is “gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)”

The following is the result returned after I run the "g++ -v" command
> Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by cjlin1** [comment]
I think your gcc version is too old. What I have is 10.2

**Comment by FrontierSetter** [comment]
Thank you very much, I upgraded the gcc version to 8.3.1 and compiled successfully
