### ISSUE TITLE
Potential Integer Overflow vulnerability in linear.cpp

### ISSUE THREAD

**Issue by KSB21ST** [cjlin1/liblinear#77]
Hi,
It seems that there exists a potential integer overflow. Please find the following description:

1. nr_feature can be an arbitrary large number
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L3539
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L3570

2. n is 1+nr_feature
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L3572

3. w_size is n
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L3575

4. Call to malloc with the large integer can cause a memory allocation with an overflowed size
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L24
https://github.com/cjlin1/liblinear/blob/60f1adf6f35d6f3e031c334b33dfe8399d6f8a9d/linear.cpp#L3582

**Comment by cjlin1** [comment]
There is this experimental code to handle very large sets:

https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/#liblinear_for_more_than_2^32_instances_features_experimental

**Comment by KSB21ST** [comment]
Thanks for the reply. Might it be possible if a malicious attacker gives enough large value that can cause Integer Overflow?
