### ISSUE TITLE
Adding support to build with cmake

### ISSUE THREAD

**Issue by carandraug** [cjlin1/liblinear#79]
It would be nice if the project also included cmake rules for the following reasons:

1. easier to build in Windows
2. easier to integrate in other projects that already use cmake (alternatively, providing pkg-config files)

Adding support for cmake does not require dropping the existing the Makefiles.

There's been two PR that tried this already. There was #42, which unfortunately mixed the addition of cmake with other non-desired features and so was closed. And there is #26 which is now 5 years old and not been acted on.  I also made my own cmake rules (it's pretty simple). 

Would be nice if this feature could be added. I can take a look at this, no problem, if there is is interest on this feature. Please let me know.

**Comment by cjlin1** [comment]
We have long realized the need of cmake for some users, but were unsure if it should be added in the package (as we try to keep it as small/simple as possible). In the end we decide to have a separate place supporting the cmake use. Please see 
https://www.csie.ntu.edu.tw/~cjlin/liblinear/FAQ.html
and
https://www.csie.ntu.edu.tw/~cjlin/liblinear/faqfiles/cmake.html
Hope this is useful for cmake users. Thanks.
