### ISSUE TITLE
ModuleNotFoundError when using multiprocessing

### ISSUE THREAD

**Issue by agkphysics** [cjlin1/liblinear#82]
I was trying to implement a custom classifier in scikit-learn using the liblinear library, and cross-validate using the `cross_validate()` method which can run multiple folds in parallel. It gives this error when running in parallel:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/akee511/src/emotion/.venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/akee511/src/emotion/src/ertk/sklearn/models/mtl.py", line 1, in <module>
    import liblinear.liblinearutil as liblinearutil
ModuleNotFoundError: No module named 'liblinear.liblinearutil'; 'liblinear' is not a package
"""
```

I have determined that it's due to adding the directory to `sys.path` in `liblinearutil.py` which seems to be unnecessary. https://github.com/cjlin1/liblinear/blob/5b973b2d7fa13409f6319d283d4b19783a350006/python/liblinear/liblinearutil.py#L4
If you remove that line the error does not occur while the code still works fine.

**Comment by cjlin1** [comment]
How does your mtl.py look like?

**Comment by agkphysics** [comment]
```python
import liblinear.liblinearutil as liblinearutil
import numpy as np
from sklearn.base import BaseEstimator, ClassifierMixin
```
I then use `liblinearutil.train()` in my classifier.

**Comment by agkphysics** [comment]
The code runs fine when run normally, just not in a multiprocessing context.

**Comment by agkphysics** [comment]
Here is a MWE:
```python
import liblinear.liblinearutil as liblinearutil
from joblib import Parallel, delayed

def f():
    liblinearutil

if __name__ == "__main__":
    Parallel(n_jobs=2)(delayed(f)() for _ in range(2))
```

Running this gives the following error:
```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/akee511/src/emotion/.venv/lib/python3.8/site-packages/joblib/externals/loky/process_executor.py", line 407, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/home/akee511/src/emotion/.venv/lib/python3.8/site-packages/joblib/externals/cloudpickle/cloudpickle.py", line 679, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'liblinear.liblinearutil'; 'liblinear' is not a package
"""
```

So it seems that the issue is with using either cloudpickle or the joblib default `loky` backend, as it doesn't occur with the `multiprocessing` backend. The problem is that scikit-learn uses the joblib default backend, so functions like `cross_validate()` don't work.

**Comment by cjlin1** [comment]
Did you pip install liblinear-official?

**Comment by agkphysics** [comment]
@cjlin1 Yes:
```
$ pip show liblinear-official
Name: liblinear-official
Version: 2.44.0
...
```

**Comment by cjlin1** [comment]
Many thanks. We have removed that line in our internal git. This update will appear here in the next release.
