### ISSUE TITLE
Problem running the example for testing LIBLINEAR with instance weight support 

### ISSUE THREAD

**Issue by ksong4** [cjlin1/liblinear#83]
I recently installed the LIBLINEAR and was testing the example scripts that were part of the README.weight

The following codes work until the problem() command
```
from liblinear.liblinearutil import *
import csv
y, x = svm_read_problem('./heart_scale', return_scipy=True)
W = [1] * len(y)
W[0] = 10
prob = problem(W, y, x) # Error occurs here 
```
The error code is shown here:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ksong4/miniconda3/lib/python3.7/site-packages/liblinear/liblinear.py", line 194, in __init__
    tmp_xi, tmp_idx = gen_feature_nodearray(xi)
  File "/home/ksong4/miniconda3/lib/python3.7/site-packages/liblinear/liblinear.py", line 106, in gen_feature_nodearray
    raise TypeError('xi should be a dictionary, list, tuple, 1-d numpy array, or tuple of (index, data)')
TypeError: xi should be a dictionary, list, tuple, 1-d numpy array, or tuple of (index, data)
```
The imported x and y are both lists using the provided example heart_scale file.

**Comment by cjlin1** [comment]
Looks like you already have liblinear in the system but would like to 
use the liblinear "weight" extension?

If you run this example in the directory
liblinear-weights-2.45/python
I believe the weight code instead of the system package will be called 
first

**Comment by ksong4** [comment]
Thank you so much for your prompt and helpful commands; I was indeed in the wrong directory when running the example.
