### ISSUE TITLE
On macOS extension should be .dylib

### ISSUE THREAD

**Issue by barracuda156** [cjlin1/liblinear#85]
It should install as `liblinear.dylib` instead.

**Comment by cjlin1** [comment]
can you elaborate more?

**Comment by barracuda156** [comment]
Standard shared library extension on macOS is .dylib. While .so is used in some specific context, it is not how shared libraries are normally installed.

**Comment by cjlin1** [comment]
Thanks. Because .so still works and in our code we have something like

    try:
        if sys.platform == 'win32':
            libsvm = CDLL(path.join(dirname, r'..\..\windows\libsvm.dll'))
        else:
            libsvm = CDLL(path.join(dirname, '../../libsvm.so.3'))

we think it may be better to keep using .so for now.
