### ISSUE TITLE
Tarball misses python sources

### ISSUE THREAD

**Issue by barracuda156** [cjlin1/liblinear#86]
Whether downloaded from here (246) or from the homepage https://www.csie.ntu.edu.tw/~cjlin/liblinear – `python` directory is empty.

**Comment by cjlin1** [comment]
I downloaded the tar.gz file and the python directory isn't empty? See details below

$ tar zxvf liblinear-2.46.tar.gz 
liblinear-2.46/
liblinear-2.46/newton.h
liblinear-2.46/linear.def
liblinear-2.46/linear.cpp
liblinear-2.46/linear.h
liblinear-2.46/README
liblinear-2.46/heart_scale
liblinear-2.46/matlab/
liblinear-2.46/matlab/make.m
liblinear-2.46/matlab/README
liblinear-2.46/matlab/Makefile
liblinear-2.46/matlab/linear_model_matlab.c
liblinear-2.46/matlab/linear_model_matlab.h
liblinear-2.46/matlab/libsvmwrite.c
liblinear-2.46/matlab/predict.c
liblinear-2.46/matlab/train.c
liblinear-2.46/matlab/libsvmread.c
liblinear-2.46/Makefile
liblinear-2.46/python/
liblinear-2.46/python/README
liblinear-2.46/python/setup.py
liblinear-2.46/python/Makefile
liblinear-2.46/python/MANIFEST.in
liblinear-2.46/python/liblinear/
liblinear-2.46/python/liblinear/liblinearutil.py
liblinear-2.46/python/liblinear/commonutil.py
liblinear-2.46/python/liblinear/liblinear.py
liblinear-2.46/python/liblinear/__init__.py
liblinear-2.46/newton.cpp
liblinear-2.46/COPYRIGHT
liblinear-2.46/.github/
liblinear-2.46/.github/workflows/
liblinear-2.46/.github/workflows/wheel.yml
liblinear-2.46/svm-scale.c
liblinear-2.46/predict.c
liblinear-2.46/windows/
liblinear-2.46/windows/liblinear.dll
liblinear-2.46/windows/libsvmwrite.mexw64
liblinear-2.46/windows/predict.exe
liblinear-2.46/windows/train.exe
liblinear-2.46/windows/train.mexw64
liblinear-2.46/windows/libsvmread.mexw64
liblinear-2.46/windows/predict.mexw64
liblinear-2.46/train.c
liblinear-2.46/Makefile.win
liblinear-2.46/blas/
liblinear-2.46/blas/dscal.c
liblinear-2.46/blas/blasp.h
liblinear-2.46/blas/blas.h
liblinear-2.46/blas/Makefile
liblinear-2.46/blas/dnrm2.c
liblinear-2.46/blas/daxpy.c
liblinear-2.46/blas/ddot.c
$ ls -al liblinear-2.46/python/
total 44
drwxr-xr-x 3 cjlin cjlin  4096 Feb 17 20:01 .
drwxr-xr-x 7 cjlin cjlin  4096 Feb 17 20:01 ..
drwxr-xr-x 2 cjlin cjlin  4096 Feb 17 20:01 liblinear
-rw-r--r-- 1 cjlin cjlin    32 Feb 17 20:01 Makefile
-rw-r--r-- 1 cjlin cjlin    46 Feb 17 20:01 MANIFEST.in
-rw-r--r-- 1 cjlin cjlin 17431 Feb 17 20:01 README
-rw-r--r-- 1 cjlin cjlin  3484 Feb 17 20:01 setup.py

**Comment by barracuda156** [comment]
Hmm, weird. Thank you, perhaps some local glitch.
