### ISSUE TITLE
Predicted class and decision scores do not match in Crammer-Singer

### ISSUE THREAD

**Issue by neurominer-git** [cjlin1/liblinear#90]
Dear Chih-Jen Lin,
sorry to bother with this question. Looking at the output of LIBLINEAR when using Crammer-Singer, I would have expected the highest absolute decision score in the predicted class. However, this is not the case:
In a 4-class problem I get a prediction of "Class 1", while the maximum decision score is in the 4. classifier:
    Class 1: -0.0115
    Class 2: -0.0631
    Class 3: 0.0302
    Class 4: 0.0444
Have I misunderstood anything?
Many thanks for your help!

**Comment by cjlin1** [comment]
Can you tell me how you print out class ID and decision values? There is 
a mapping between internal and real labels. For example, think about 
that your real labels are 5,6,7,8 instead.
